add norm test

diff --git a/.github/workflows/c_tests.yml b/.github/workflows/c_tests.yml
--- a/.github/workflows/c_tests.yml
+++ b/.github/workflows/c_tests.yml
@@ -27,6 +27,22 @@ jobs:
         sudo apt-get install -y build-essential
         sudo apt-get install -y libreadline8 libreadline-dev
         sudo apt-get install -y libcriterion-dev
+
+    - name: Install Norminette
+      run: |
+        python3 -m pip install --upgrade pip setuptools
+        python3 -m pip install norminette
+        
+    - name: Run Norminette check
+      run: |
+        echo "Running Norminette check on srcs/ and includes/"
+        norminette srcs/ includes/
+        if [ $? -ne 0 ]; then
+          echo "Norminette check failed!"
+          exit 1
+        fi
+        echo "Norminette check passed!"
+      
     - name: Install coverage tools
       run: |
         sudo apt-get install -y lcov
